#!/usr/bin/env python3

texts = {
	"HEADER_START": """/* This file has been generated by flow2code
* See: https://flow.liwe.org
*/

import { ILRequest, ILResponse, ILError, ILiWE } from '../../liwe/types';
import { send_error, send_ok, typed_dict } from "../../liwe/utils";
import { locale_load } from '../../liwe/locale';

import { perms } from '../../liwe/auth';

import {
	%(_methods)s
} from './methods';

import {
	User, UserActivationCode, UserFaceRec, UserPerms, UserRegistration, UserSessionData
} from './types';

// d2r_start __header
%(__header)s
// d2r_end __header

export const init = ( liwe: ILiWE ) => {
	const app = liwe.app;

	console.log( "    - %(__name_camel)s " );

	liwe.cfg.app.languages.map( ( l ) => locale_load( "user", l ) );
	user_db_init ( liwe );

"""
}