#!/usr/bin/env python3

texts = {
	"HEADER_START": """/* This file has been generated by flow2code
* See: https://flow.liwe.org
*/

import { ILRequest, ILResponse, ILError, ILiWE } from '../../liwe/types';
import { send_error, send_ok, typed_dict } from "../../liwe/utils";
import { locale_load } from '../../liwe/locale';

import { perms } from '../../liwe/auth';

import {
	// endpoints function
	%(__methods)s
	// functions
	%(__functions)s
} from './methods';

import {
	%(__interfaces)s
} from './types';

/*=== f2c_start __header ===*/
%(__header)s
/*=== f2c_end __header ===*/

export const init = ( liwe: ILiWE ) => {
	const app = liwe.app;

	console.log( "    - %(__name_camel)s " );

	liwe.cfg.app.languages.map( ( l ) => locale_load( "%(__name_lower)s", l ) );
	%(__name_lower)s_db_init ( liwe );
""",
	"HEADER_END": """
};
""",

	"ENDPOINT": """
	app.%(__method_lower)s ( '/api%(url)s', %(__perms)s( req: ILRequest, res: ILResponse ) => {
		%(__typed_dict)s

		%(__endpoint_name)s ( req, %(__params)s( err: ILError, %(__return_var_name)s: %(__return_type)s ) => {
			if ( err ) return send_error( res, err );

			send_ok( res, { %(__spread)s%(__return_var_name)s } );
		} );
	} );
""",
		"TYPED_DICT": '{ name: "%(name)s", type: "%(type)s"%(_req_param)s }',
		"TYPED_DICT_OBJ": '{ name: "%(name)s", type: %(type)sObj%(_req_param)s }',
		"METHODS_FILE_START": """
import { ILRequest, ILResponse, LCback, ILiweConfig, ILError, ILiWE } from '../../liwe/types';
import { mkid } from '../../liwe/utils';
import { collection_add, collection_count, collection_count_dict, collection_find_all, collection_find_one, collection_find_one_dict, collection_find_all_dict, collection_del_one_dict, collection_del_all_dict, collection_init, prepare_filters } from '../../liwe/arangodb';
import { DocumentCollection } from 'arangojs/collection';
import { $l } from '../../liwe/locale';

import {
	%(__interfaces)s
} from './types';

let _liwe: ILiWE = null;

const _ = ( txt: string, vals: any = null, plural = false ) => {
	return $l( txt, vals, plural, "%(__name_lower)s" );
};

%(__collections)s

/*=== f2c_start __file_header === */
%(__file_header)s
/*=== f2c_end __file_header ===*/

""",
	"METHODS_FILE_END": """\n""",
	"TYPE_COLL_VAR": "let _coll_%s: DocumentCollection = null;",
	"TYPE_COLL_CONST": 'const COLL_%s = "%s";',

	"FOLDING_EP_START": """// {{{ %(endpoint_name)s ( req: ILRequest, %(__parameters)scback: LCBack = null ): Promise<%(return_type)s>""",
	"FOLDING_FN_START": """// {{{ %(function_name)s ( %(__parameters)scback: LCBack = null ): Promise<%(return_type)s>""",
	"FOLDING_END": """// }}}\n\n""",
	"EP_TYPED_PARAM": "%(name)s%(opt)s: %(type)s%(param_default)s",
	"EP_DOC_FIELD": "@param %(name)s - %(doc)s [%(_is_req)s]",
	"EP_DOC_RETURN": "@return %(name)s: %(return_type)s%(doc)s",
	"DB_INDEX": """{ type: "%(_type)s", fields: [ "%(_name)s" ], unique: %(_unique)s },""",
	"COLL_DEF": """%(coll_name)s = await collection_init( liwe.db, %(table_name)s, [\n\t\t\t%(rows)s\n\t\t], %(coll_drop)s );\n""",
	"EP_START": """
/**
 *
%(__description)s
 */
export const %(endpoint_name)s = ( req: ILRequest, %(__parameters)scback: LCback = null ): Promise<%(return_type)s> => {
	return new Promise( async ( resolve, reject ) => {
		/*=== f2c_start %(endpoint_name)s ===*/
%(__snippet)s""",
		"EP_END": """
		/*=== f2c_end %(endpoint_name)s ===*/
	} );
};
""",
		"FUNCTION_START": """
/**
 *
%(__description)s
 */
export const %(function_name)s = ( %(__parameters)scback: LCback = null ): Promise<%(return_type)s> => {
	return new Promise( async ( resolve, reject ) => {
%(__pre_snip)s		/*=== f2c_start %(function_name)s ===*/
%(__snippet)s
""",
		"FUNCTION_END": """		/*=== f2c_end %(function_name)s ===*/
	} );
};
""",
	"TYPES_FILE_START": """/* Types file generated by flow2code */

/*=== f2c_start __file ===*/
%(__file)s
/*=== f2c_end __file ===*/

""",
	"TYPES_FILE_END": "",
	"ENUM_START": """/** %(name)s%(description)s */
export enum %(name)s {\n""",
	"ENUM_END": """};\n\n""",
	"ENUM_ROW": """\t/** %(description)s */
	%(name)s = "%(val)s",\n""",

	"ENUM_OBJ_START": """export const %(name)sObj = {
	__name: "%(name)s",\n""",
	"ENUM_OBJ_END": """};\n\n""",
	"ENUM_OBJ_ROW": """\t%(name)s: "%(val)s",\n""",
	"INTERFACE_START": """/** %(name)s */
export interface %(name)s {
""",
	"INTERFACE_END": """}\n\n""",
	"INTERFACE_KEYS_START": """export const %(name)sKeys = {
""",
	"INTERFACE_KEYS_END": """};\n\n""",
	"INTERFACE_PARAM": "	/** %(description)s */\n	%(name)s?: %(type)s;\n",
	"INTERFACE_KEY_PARAM": "	'%(name)s': { type: '%(type)s', priv: %(private)s },\n",
}