#!/usr/bin/env python3

texts = {
    "TYPE_FILE_START": """/* Type file generated by flow2code */
// ignore_for_file: non_constant_identifier_names


/*=== f2c_start __file ===*/
%(__file)s
/*=== f2c_end __file ===*/

""",
    "TYPE_FILE_END": "",
    "INTERFACE_START": """/// %(name)s
class %(name)s {
""",
    "INTERFACE_END": """}\n\n""",
    "INTERFACE_PARAM": "\n  /// %(description)s\n	%(final)s%(type)s%(opt)s %(name)s;\n",
    "INTERFACE_PARAM_NO_DESCR": "  %(final)s%(type)s%(opt)s %(name)s;\n",
    "PARAM_REQUIRED": "required this.%(name)s",
    "PARAM_OPTIONAL": "this.%(name)s",
    "CONSTRUCTOR": """\n  %(name)s(
      {%(_constructor_params)s}) {
    /*=== f2c_start __constructor ===*/
%(__constructor)s
    /*=== f2c_end __constructor ===*/
  }

  /*=== f2c_start __methods ===*/
%(__methods)s
  /*=== f2c_end __methods ===*/
""",
}
